// 文档生成公共部分：Doc 构建器、链接、状态/招式等文字（中英双语，调用前需已设置语言）
import { writeFileSync, mkdirSync } from 'node:fs';
import { lang, tx } from '../../src/i18n';
import { CHAPTERS } from '../../src/data/chapters';
import { ENEMIES, type EnemyDef } from '../../src/data/enemies';
import { BOSSES, type BossDef, type Pattern } from '../../src/data/bosses';
import { WEAPONS, type WeaponDef } from '../../src/data/weapons';
import { STATUSES, type StatusApply, type StatusId } from '../../src/data/statuses';
import { describeMods } from '../../src/data/stats';
import type { CharacterDef } from '../../src/data/characters';
import { ACH_MAP } from '../../src/data/achievements';
import { achText, tierLabel, charCost } from '../../src/systems/Achievements';

export const outDir = () => (lang === 'en' ? 'docs/en' : 'docs');

const docs = () =>
  [
    ['README', lang === 'en' ? '../../README.en.md' : '../README.md'],
    [tx('角色', 'Characters'), 'CHARACTERS.md'],
    [tx('技能', 'Skills'), 'SKILLS.md'],
    [tx('武器', 'Weapons'), 'WEAPONS.md'],
    [tx('道具', 'Items'), 'ITEMS.md'],
    [tx('怪物', 'Monsters'), 'MONSTERS.md'],
    [tx('关卡', 'Chapters'), 'CHAPTERS.md'],
    [tx('成就', 'Achievements'), 'ACHIEVEMENTS.md'],
    [tx('天赋', 'Talents'), 'TALENTS.md'],
    [tx('设计文档', 'Design Doc'), 'GDD.md'],
    [tx('数值表', 'Data Tables'), 'DATA_TABLES.md'],
    [tx('更新日志', 'Changelog'), 'CHANGELOG.md'],
  ] as const;

export const navLine = (file: string) => docs().map(([n, f]) => (f === file ? `**${n}**` : `[${n}](${f})`)).join(' · ');
export const langLine = (file: string) => (lang === 'en' ? `[中文](../${file}) · **English**` : `**中文** · [English](en/${file})`);
export const generatedNote = () => tx('> 由 `npm run docs` 从 `src/data/*.ts` 自动生成，请勿手改。', '> Generated by `npm run docs` from `src/data/*.ts`. Do not edit by hand.');

export class Doc {
  private body: string[] = [];
  private toc: string[] = [];
  constructor(
    private file: string,
    private title: string,
    private intro: string[],
  ) {}
  h2(text: string, id: string) {
    this.toc.push(`- [${text}](#${id})`);
    this.body.push(`<a id="${id}"></a>`, '', `## ${text}`, '');
  }
  h3(text: string, id: string, inToc = true) {
    if (inToc) this.toc.push(`  - [${text}](#${id})`);
    this.body.push(`<a id="${id}"></a>`, '', `### ${text}`, '');
  }
  p(...lines: string[]) {
    this.body.push(...lines, '');
  }
  table(head: string[], rows: (string | number)[][]) {
    this.body.push(`| ${head.join(' | ')} |`, `| ${head.map(() => '---').join(' | ')} |`);
    for (const r of rows) this.body.push(`| ${r.map((c) => String(c).replace(/\|/g, '\\|').replace(/\n/g, '<br>')).join(' | ')} |`);
    this.body.push('');
  }
  write() {
    const nav = navLine(this.file);
    const out = [`# ${this.title}`, '', langLine(this.file), '', nav, '', generatedNote(), '', ...this.intro, '', `## ${tx('目录', 'Contents')}`, '', ...this.toc, '', ...this.body, '---', '', nav, ''];
    mkdirSync(outDir(), { recursive: true });
    writeFileSync(`${outDir()}/${this.file}`, out.join('\n'));
  }
}

/** 文档图片（由 npm run docs:images 从游戏程序化绘制导出） */
export type ImgKind = 'char' | 'weapon' | 'item' | 'enemy' | 'boss';
export const img = (kind: ImgKind, id: string, size = 32) =>
  `<img src="${lang === 'en' ? '../' : ''}images/${kind}/${id}.png" width="${size}" height="${size}" alt="">`;

export const ENEMY_MAP: Record<string, EnemyDef> = Object.fromEntries(ENEMIES.map((e) => [e.id, e]));
export const WEAPON_MAP: Record<string, WeaponDef> = Object.fromEntries(WEAPONS.map((w) => [w.id, w]));
export const ELITES = BOSSES.filter((b) => b.elite);
export const BOSS_ONLY = BOSSES.filter((b) => !b.elite);

export const lnk = {
  char: (c: CharacterDef, f = 'CHARACTERS.md') => `[${c.name}](${f}#char-${c.id})`,
  skill: (c: CharacterDef, f = 'SKILLS.md') => `[${c.skill.name}](${f}#skill-${c.id})`,
  weapon: (id: string, f = 'WEAPONS.md') => `[${WEAPON_MAP[id]?.name ?? id}](${f}#weapon-${id})`,
  enemy: (id: string, f = 'MONSTERS.md') => `[${ENEMY_MAP[id]?.name ?? id}](${f}#enemy-${id})`,
  boss: (b: BossDef, f = 'MONSTERS.md') => `[${b.name}](${f}#boss-${b.id})`,
  chapter: (id: number, f = 'CHAPTERS.md') => `[${CHAPTERS.find((c) => c.id === id)?.name ?? id}](${f}#chapter-${id})`,
  status: (id: StatusId, f = 'SKILLS.md') => `[${STATUSES[id].name}](${f}#status-${id})`,
};

export const sep = () => tx('、', ', ');
/** 角色解锁方式：默认 / 成就点价格（+ 前置成就链接） */
export function unlockText(c: CharacterDef, f = 'ACHIEVEMENTS.md'): string {
  if (!c.cost) return tx('默认解锁', 'Unlocked by default');
  const price = tx(`${charCost(c)} 成就点`, `${charCost(c)} pts`);
  if (!c.requires) return price;
  const a = ACH_MAP[c.requires.ach];
  const tl = tierLabel(a, c.requires.tier);
  const req = `[${achText(a, 'name', c.requires.tier - 1)}${tl ? `（${tl}）` : ''}](${f}#ach-${a.id})`;
  return tx(`${price}，需先达成 ${req}`, `${price}, requires ${req}`);
}
/** 状态施加：3层[减速](..) 3s（30%） */
export const stApply = (l: StatusApply[] | undefined, f?: string) =>
  (l ?? [])
    .map(
      (a) =>
        `${a.stacks && a.stacks > 1 ? a.stacks + tx('层', '× ') : ''}${lnk.status(a.id, f)} ${a.dur}s${a.chance !== undefined && a.chance < 100 ? tx(`（${a.chance}%）`, ` (${a.chance}%)`) : ''}`,
    )
    .join(sep());
export const mods = (m: CharacterDef['mods'] | undefined) => describeMods(m ?? {}).join(tx('，', ', '));

export const CLS_NAME = () => ({ melee: tx('近战', 'Melee'), ranged: tx('远程', 'Ranged'), elemental: tx('元素', 'Elemental') });
export const KIND_NAME = (): Record<string, string> => ({
  thrust: tx('直刺', 'Thrust'),
  sweep: tx('横扫', 'Sweep'),
  bullet: tx('子弹', 'Bullet'),
  rocket: tx('爆炸弹', 'Rocket'),
  flame: tx('喷火', 'Flame'),
  aura: tx('光环', 'Aura'),
  mine: tx('地雷', 'Mine'),
  boomerang: tx('回旋镖', 'Boomerang'),
  chain: tx('连锁闪电', 'Chain Lightning'),
});
export const BEHAVIOR_NAME = (): Record<string, string> => ({
  chase: tx('追击', 'Chase'),
  wander: tx('游荡', 'Wander'),
  charger: tx('蓄力冲撞', 'Charger'),
  shooter: tx('远程射击', 'Shooter'),
  bomber: tx('自爆', 'Bomber'),
  splitter: tx('死亡分裂', 'Splits on death'),
  healer: tx('治疗同伴', 'Healer'),
  summoner: tx('召唤', 'Summoner'),
  trail: tx('留下黏液', 'Slime trail'),
  flee: tx('逃窜', 'Flee'),
});
const PATTERN_NAME = (): Record<string, string> => ({
  ring: tx('环形弹', 'Ring'),
  spiral: tx('螺旋弹幕', 'Spiral'),
  aimed: tx('扇形瞄准', 'Aimed fan'),
  scatter: tx('乱射', 'Scatter'),
  charge: tx('预警冲锋', 'Telegraphed charge'),
  slam: tx('预警砸地', 'Telegraphed slam'),
  hazard: tx('危险区', 'Hazard zone'),
  laser: tx('预警激光', 'Telegraphed laser'),
  teleport: tx('瞬移', 'Teleport'),
  summon: tx('召唤', 'Summon'),
  buff: tx('强化', 'Empower'),
});
export const describePattern = (p: Pattern) => {
  const bits = [PATTERN_NAME()[p.type] ?? p.type];
  if (p.type === 'summon' && p.enemy) bits.push(tx(`${p.count ?? 1} 只${lnk.enemy(p.enemy)}`, `${p.count ?? 1}× ${lnk.enemy(p.enemy)}`));
  else if (p.count) bits.push(`×${p.count}`);
  if (p.debuff) bits.push(tx(`命中附带 ${stApply(p.debuff)}`, `inflicts ${stApply(p.debuff)}`));
  if (p.buff) bits.push(tx(`自身/同伴获得 ${stApply(p.buff)}`, `self/allies gain ${stApply(p.buff)}`));
  return `${bits.join(' ')}${tx(`（每 ${p.cd}s）`, ` (every ${p.cd}s)`)}`;
};
export const waveRange = (from: number, to?: number) => `${from}${to ? '~' + to : '+'}`;
/** 每种小怪出现在哪些章节、哪些波次 */
export const enemyAppear = (id: string) =>
  CHAPTERS.flatMap((c) =>
    c.pool.filter((p) => p.enemy === id).map((p) => `${lnk.chapter(c.id)} ${tx(`第 ${waveRange(p.from, p.to)} 波`, `waves ${waveRange(p.from, p.to)}`)}`),
  );
